# syntax=docker/dockerfile:1
FROM ruby:3.3.1-slim

WORKDIR /rails

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
    curl libjemalloc2 libvips postgresql-client build-essential git libpq-dev pkg-config \
    nodejs yarn && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

# Copiar Gemfile e instalar as gems
COPY Gemfile Gemfile.lock ./
RUN bundle install

# Copiar código do app
COPY . .

# Expor a porta do Rails
EXPOSE 3000

# Ao iniciar o contêiner, criar/migrar o banco e iniciar o servidor Rails
CMD bash -c "rm -f tmp/pids/server.pid && bin/rails db:prepare && bin/rails server -b 0.0.0.0 -p 3000"
