default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: yes_bt_development

test:
  <<: *default
  database: yes_bt_test


production:
  <<: *default
  database: yes_bt_production
  username: yes_bt
  password: <%= ENV["YES_BT_DATABASE_PASSWORD"] %>
